# Generated by Django 4.0 on 2022-06-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hero', models.CharField(max_length=100)),
                ('heroine', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('rating', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
